/**
 * Full-lifecycle e2e for ENACT v2 on testnet. Exercises the happy
 * path and the reject path with TWO wallets:
 *   * CLIENT (= maintainer wallet from WALLET_MNEMONIC; acts as
 *     evaluator too for brevity — self-evaluation is allowed by
 *     design and documented in the whitepaper)
 *   * PROVIDER (PROVIDER_MNEMONIC from .env.local, generated by
 *     scripts/gen-provider-wallet.ts)
 *
 * Scenarios:
 *   1. happy path TON: create -> fund -> take (provider) ->
 *      submit (provider) -> approve (evaluator) -> reach
 *      SETTLING_COMPLETED, CommitSettlement -> COMPLETED.
 *   2. reject path TON: create -> fund -> take (provider) ->
 *      submit (provider) -> reject (evaluator) -> reach
 *      SETTLING_DISPUTED, CommitSettlement -> DISPUTED.
 *
 * Each scenario verifies BUG-1 coverage implicitly: the contract
 * first enters SETTLING_* (two-phase settlement) and only transitions
 * to COMPLETED/DISPUTED once the payout has drained and
 * CommitSettlement has been called.
 *
 * Run: npx ts-node scripts/e2e-testnet-fullcycle.ts
 */
import {
    Address,
    Cell,
    OpenedContract,
    SendMode,
    TonClient,
    WalletContractV5R1,
    beginCell,
    internal,
    toNano,
} from '@ton/ton';
import { KeyPair, mnemonicToPrivateKey } from '@ton/crypto';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

import { JobOpcodes } from '../wrappers/Job';
import { buildV2InitParams, FactoryOpcodes } from '../wrappers/JobFactory';

dotenv.config({ path: path.join(__dirname, '..', '.env.local') });

const MNEMONIC = (process.env.WALLET_MNEMONIC ?? '').trim();
const PROVIDER_MNEMONIC = (process.env.PROVIDER_MNEMONIC ?? '').trim();
const API_KEY = process.env.TONCENTER_API_KEY ?? '';
const ENDPOINT =
    process.env.TONCENTER_ENDPOINT ?? 'https://testnet.toncenter.com/api/v2/jsonRPC';
const TESTNET = ENDPOINT.includes('testnet');

if (!MNEMONIC || !PROVIDER_MNEMONIC) {
    console.error('WALLET_MNEMONIC and PROVIDER_MNEMONIC required in .env.local');
    console.error('run: npx ts-node scripts/gen-provider-wallet.ts first');
    process.exit(1);
}

type Report = {
    scenario: string;
    result: 'pass' | 'fail';
    details: string;
    jobAddress?: string;
    explorer?: string;
};
const report: Report[] = [];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function retry<T>(fn: () => Promise<T>, attempts = 6, delay = 3000): Promise<T> {
    for (let i = 0; i < attempts; i++) {
        try {
            return await fn();
        } catch (e: any) {
            if (i === attempts - 1) throw e;
            console.log(`  retry ${i + 1}/${attempts}: ${String(e.message ?? e).slice(0, 80)}`);
            await sleep(delay);
        }
    }
    throw new Error('unreachable');
}

function explorerUrl(addr: Address) {
    return `https://${TESTNET ? 'testnet.' : ''}tonviewer.com/${addr.toString({ testOnly: TESTNET })}`;
}

async function waitForSeqno(w: any, expected: number): Promise<number> {
    for (let i = 0; i < 40; i++) {
        await sleep(2500);
        const s: number = await retry(() => w.getSeqno());
        if (s >= expected) return s;
    }
    throw new Error('seqno did not advance');
}

async function getJobState(client: TonClient, addr: Address): Promise<number | null> {
    try {
        const r = await retry(() => client.runMethod(addr, 'get_state', []));
        return Number(r.stack.readBigNumber());
    } catch {
        return null;
    }
}

async function getJobData(client: TonClient, addr: Address) {
    const r = await retry(() => client.runMethod(addr, 'get_job_data', []));
    return {
        jobId: Number(r.stack.readBigNumber()),
        client: r.stack.readAddress(),
        provider: r.stack.readAddressOpt(),
        evaluator: r.stack.readAddress(),
        budget: r.stack.readBigNumber(),
        descriptionHash: r.stack.readBigNumber(),
        resultHash: r.stack.readBigNumber(),
        timeout: Number(r.stack.readBigNumber()),
        createdAt: Number(r.stack.readBigNumber()),
        evalTimeout: Number(r.stack.readBigNumber()),
        submittedAt: Number(r.stack.readBigNumber()),
        resultType: Number(r.stack.readBigNumber()),
        reason: r.stack.readBigNumber(),
        state: Number(r.stack.readBigNumber()),
    };
}

async function getNextJobId(client: TonClient, addr: Address): Promise<number> {
    const r = await retry(() => client.runMethod(addr, 'get_next_job_id', []));
    return Number(r.stack.readBigNumber());
}

async function getJobAddress(client: TonClient, factory: Address, jobId: number): Promise<Address> {
    const r = await retry(() =>
        client.runMethod(factory, 'get_job_address', [{ type: 'int', value: BigInt(jobId) }]),
    );
    return r.stack.readAddress();
}

async function waitForState(
    client: TonClient,
    addr: Address,
    predicate: (s: number) => boolean,
    label: string,
    maxWaits = 50,
) {
    for (let i = 0; i < maxWaits; i++) {
        const s = await getJobState(client, addr);
        if (s !== null && predicate(s)) {
            console.log(`    ${label} -> state ${s} (~${(i + 1) * 3}s)`);
            return s;
        }
        await sleep(3000);
    }
    throw new Error(`${label} timed out`);
}

async function sendMsg(
    wallet: any,
    kp: KeyPair,
    dest: Address,
    value: bigint,
    body: Cell,
    seqno: number,
): Promise<number> {
    await retry(() =>
        wallet.sendTransfer({
            seqno,
            secretKey: kp.secretKey,
            sendMode: SendMode.PAY_GAS_SEPARATELY,
            messages: [internal({ to: dest, value, body, bounce: true })],
        }),
    );
    return await waitForSeqno(wallet, seqno + 1);
}

async function createJob(
    wallet: any,
    kp: KeyPair,
    client: TonClient,
    factoryAddr: Address,
    params: {
        evaluatorAddress: Address;
        budget: bigint;
        descriptionHash: bigint;
    },
    seqno: number,
): Promise<{ jobAddr: Address; newSeqno: number }> {
    const nextId = await getNextJobId(client, factoryAddr);
    const v2 = buildV2InitParams({});
    const body = beginCell()
        .storeUint(FactoryOpcodes.createJob, 32)
        .storeAddress(params.evaluatorAddress)
        .storeCoins(params.budget)
        .storeUint(params.descriptionHash, 256)
        .storeUint(3600, 32)
        .storeUint(3600, 32)
        .storeRef(v2)
        .endCell();
    const newSeqno = await sendMsg(wallet, kp, factoryAddr, toNano('0.1'), body, seqno);

    const jobAddr = await getJobAddress(client, factoryAddr, nextId);
    await waitForState(client, jobAddr, (s) => s === 0, 'createJob');
    return { jobAddr, newSeqno };
}

async function runLifecycle(
    label: string,
    approve: boolean,
    clientWallet: any,
    clientKp: KeyPair,
    providerWallet: any,
    providerKp: KeyPair,
    client: TonClient,
    factoryAddr: Address,
    clientSeqno: number,
    providerSeqno: number,
): Promise<{ clientSeqno: number; providerSeqno: number }> {
    console.log(`\n--- ${label} (approve=${approve}) ---`);
    // Budget > CommitSettlement gas is load-bearing: the contract uses
    // `getOriginalBalance() < budget` to prove the payout has drained.
    // originalBalance is balance-at-start-of-compute which INCLUDES the
    // incoming msg.value, so budget must be strictly greater than
    // (MIN_STORAGE + commitSettlement msg.value) or the assert fires
    // with ERR_SETTLEMENT_NOT_DRAINED (110).
    const budget = toNano('0.2');
    const descHash = BigInt('0x' + (approve ? 'a1' : 'd0').repeat(32));
    const resultHash = BigInt('0x' + 'b2'.repeat(32));

    // 1. create
    const { jobAddr, newSeqno: cs1 } = await createJob(
        clientWallet,
        clientKp,
        client,
        factoryAddr,
        { evaluatorAddress: clientWallet.address, budget, descriptionHash: descHash },
        clientSeqno,
    );
    console.log(`  job: ${jobAddr.toString({ testOnly: TESTNET })}`);
    console.log(`  explorer: ${explorerUrl(jobAddr)}`);

    // 2. fund
    const fundBody = beginCell().storeUint(JobOpcodes.fund, 32).endCell();
    const cs2 = await sendMsg(clientWallet, clientKp, jobAddr, budget + toNano('0.1'), fundBody, cs1);
    await waitForState(client, jobAddr, (s) => s === 1, 'FUNDED');

    // 3. take (provider)
    const takeBody = beginCell().storeUint(JobOpcodes.takeJob, 32).endCell();
    const ps1 = await sendMsg(providerWallet, providerKp, jobAddr, toNano('0.05'), takeBody, providerSeqno);
    // Poll for provider assignment.
    for (let i = 0; i < 30; i++) {
        const d = await getJobData(client, jobAddr);
        if (d.provider !== null && d.provider.equals(providerWallet.address)) {
            console.log(`    provider assigned (~${(i + 1) * 3}s)`);
            break;
        }
        await sleep(3000);
    }

    // 4. submit (provider)
    const submitBody = beginCell()
        .storeUint(JobOpcodes.submitResult, 32)
        .storeUint(resultHash, 256)
        .storeUint(0, 8)
        .endCell();
    const ps2 = await sendMsg(providerWallet, providerKp, jobAddr, toNano('0.05'), submitBody, ps1);
    await waitForState(client, jobAddr, (s) => s === 2, 'SUBMITTED');

    // 5. evaluate (client = evaluator)
    const evalBody = beginCell()
        .storeUint(JobOpcodes.evaluate, 32)
        .storeUint(approve ? 1 : 0, 8)
        .storeUint(0n, 256)
        .endCell();
    const cs3 = await sendMsg(clientWallet, clientKp, jobAddr, toNano('0.2'), evalBody, cs2);

    // Settle path enters SETTLING_* before payout drains.
    const expectedSettling = approve ? 6 : 7;
    await waitForState(client, jobAddr, (s) => s === expectedSettling, `SETTLING_${approve ? 'COMPLETED' : 'DISPUTED'}`);

    // 6. CommitSettlement — anyone can call; the payout recipient is
    //    natural choice (provider on approve, client on reject).
    const commitBody = beginCell().storeUint(JobOpcodes.commitSettlement, 32).endCell();
    let cs4 = cs3;
    let ps3 = ps2;
    if (approve) {
        ps3 = await sendMsg(providerWallet, providerKp, jobAddr, toNano('0.05'), commitBody, ps2);
    } else {
        cs4 = await sendMsg(clientWallet, clientKp, jobAddr, toNano('0.05'), commitBody, cs3);
    }

    const expectedFinal = approve ? 3 : 4; // COMPLETED or DISPUTED
    try {
        await waitForState(client, jobAddr, (s) => s === expectedFinal, `FINAL_${approve ? 'COMPLETED' : 'DISPUTED'}`);
        report.push({
            scenario: label,
            result: 'pass',
            details: `lifecycle reached state ${expectedFinal} via two-phase settlement`,
            jobAddress: jobAddr.toString({ testOnly: TESTNET }),
            explorer: explorerUrl(jobAddr),
        });
    } catch (e) {
        const d = await getJobData(client, jobAddr);
        report.push({
            scenario: label,
            result: 'fail',
            details: `stuck in state ${d.state} (expected ${expectedFinal})`,
            jobAddress: jobAddr.toString({ testOnly: TESTNET }),
            explorer: explorerUrl(jobAddr),
        });
    }

    return { clientSeqno: cs4, providerSeqno: ps3 };
}

async function main() {
    console.log('--- ENACT v2 full-lifecycle e2e ---');
    const dep = JSON.parse(
        fs.readFileSync(
            path.join(__dirname, '..', 'deployments', TESTNET ? 'testnet-v2.json' : 'mainnet-v2.json'),
            'utf-8',
        ),
    );
    const factoryAddr = Address.parse(dep.factory.address);
    console.log(`factory: ${dep.factory.address}`);

    const client = new TonClient({ endpoint: ENDPOINT, apiKey: API_KEY });
    const clientKp = await mnemonicToPrivateKey(MNEMONIC.split(/\s+/));
    const clientWallet = client.open(
        WalletContractV5R1.create({ publicKey: clientKp.publicKey, workchain: 0 }),
    );
    const providerKp = await mnemonicToPrivateKey(PROVIDER_MNEMONIC.split(/\s+/));
    const providerWallet = client.open(
        WalletContractV5R1.create({ publicKey: providerKp.publicKey, workchain: 0 }),
    );

    const clientBal = await retry(() => clientWallet.getBalance());
    const providerBal = await retry(() => providerWallet.getBalance());
    console.log(`client:   ${clientWallet.address.toString({ testOnly: TESTNET })} — ${Number(clientBal) / 1e9} TON`);
    console.log(`provider: ${providerWallet.address.toString({ testOnly: TESTNET })} — ${Number(providerBal) / 1e9} TON`);

    if (clientBal < toNano('1') || providerBal < toNano('0.5')) {
        console.error('need at least 1 TON on client and 0.5 TON on provider');
        process.exit(1);
    }

    let cs = await retry(() => clientWallet.getSeqno());
    let ps = await retry(() => providerWallet.getSeqno());

    ({ clientSeqno: cs, providerSeqno: ps } = await runLifecycle(
        'Happy path TON (approve -> COMPLETED)',
        true,
        clientWallet,
        clientKp,
        providerWallet,
        providerKp,
        client,
        factoryAddr,
        cs,
        ps,
    ));

    ({ clientSeqno: cs, providerSeqno: ps } = await runLifecycle(
        'Reject path TON (disapprove -> DISPUTED)',
        false,
        clientWallet,
        clientKp,
        providerWallet,
        providerKp,
        client,
        factoryAddr,
        cs,
        ps,
    ));

    console.log('\n\n============================================================');
    console.log('FULL-LIFECYCLE REPORT');
    console.log('============================================================');
    const passes = report.filter((r) => r.result === 'pass').length;
    const fails = report.filter((r) => r.result === 'fail').length;
    for (const r of report) {
        const icon = r.result === 'pass' ? '✅' : '❌';
        console.log(`\n${icon} ${r.scenario}`);
        console.log(`   ${r.details}`);
        if (r.jobAddress) console.log(`   job: ${r.jobAddress}`);
        if (r.explorer) console.log(`   ${r.explorer}`);
    }
    console.log('\n-------');
    console.log(`summary: ${passes} pass, ${fails} fail, ${report.length} total`);

    const outPath = path.join(
        __dirname,
        '..',
        'deployments',
        TESTNET ? 'testnet-v2-fullcycle.json' : 'mainnet-v2-fullcycle.json',
    );
    fs.writeFileSync(
        outPath,
        JSON.stringify({ runAt: new Date().toISOString(), passes, fails, report }, null, 2) + '\n',
    );
    console.log(`saved: ${path.relative(process.cwd(), outPath)}`);
    if (fails > 0) process.exit(2);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
