/**
 * Generate a fresh V5R1 provider wallet for e2e tests, fund it from
 * the maintainer wallet in .env.local, and append PROVIDER_MNEMONIC +
 * PROVIDER_ADDRESS to .env.local.
 *
 * Run once per environment (testnet / mainnet). Network is chosen by
 * TONCENTER_ENDPOINT in .env.local.
 *
 * Never commits the new seed — .env.local is gitignored.
 */
import {
    SendMode,
    TonClient,
    WalletContractV5R1,
    internal,
    toNano,
} from '@ton/ton';
import { mnemonicNew, mnemonicToPrivateKey } from '@ton/crypto';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

const ENV_PATH = path.join(__dirname, '..', '.env.local');
dotenv.config({ path: ENV_PATH });

const MNEMONIC = (process.env.WALLET_MNEMONIC ?? '').trim();
const API_KEY = process.env.TONCENTER_API_KEY ?? '';
const ENDPOINT =
    process.env.TONCENTER_ENDPOINT ?? 'https://testnet.toncenter.com/api/v2/jsonRPC';
const FUND_TON = process.env.PROVIDER_FUND_TON ?? '5';
const TESTNET = ENDPOINT.includes('testnet');

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function retry<T>(fn: () => Promise<T>, attempts = 6, delay = 3000): Promise<T> {
    for (let i = 0; i < attempts; i++) {
        try {
            return await fn();
        } catch (e: any) {
            if (i === attempts - 1) throw e;
            console.log(`  retry ${i + 1}/${attempts}: ${String(e.message ?? e).slice(0, 80)}`);
            await sleep(delay);
        }
    }
    throw new Error('unreachable');
}

async function main() {
    if (!MNEMONIC) {
        console.error('WALLET_MNEMONIC missing in .env.local');
        process.exit(1);
    }

    console.log('--- Provider wallet generator ---');
    console.log(`endpoint: ${ENDPOINT}`);

    // If PROVIDER_MNEMONIC already present, skip generation and just
    // confirm/rebalance. Keeps the script idempotent across reruns.
    const existing = (process.env.PROVIDER_MNEMONIC ?? '').trim();
    let providerWords: string[];
    if (existing) {
        providerWords = existing.split(/\s+/);
        console.log('PROVIDER_MNEMONIC already in .env.local — reusing');
    } else {
        providerWords = await mnemonicNew(24);
        console.log('generated fresh 24-word provider mnemonic');
    }

    const providerKp = await mnemonicToPrivateKey(providerWords);
    const providerWallet = WalletContractV5R1.create({
        publicKey: providerKp.publicKey,
        workchain: 0,
    });
    const providerAddr = providerWallet.address.toString({ testOnly: TESTNET });
    console.log(`provider address: ${providerAddr}`);

    const client = new TonClient({ endpoint: ENDPOINT, apiKey: API_KEY });
    const balanceBefore = await retry(() => client.getBalance(providerWallet.address));
    console.log(`provider balance before: ${Number(balanceBefore) / 1e9} TON`);

    if (balanceBefore < toNano(FUND_TON)) {
        const mainKp = await mnemonicToPrivateKey(MNEMONIC.split(/\s+/));
        const mainWallet = WalletContractV5R1.create({
            publicKey: mainKp.publicKey,
            workchain: 0,
        });
        const w = client.open(mainWallet);
        const mainBalance = await retry(() => w.getBalance());
        console.log(`main wallet balance: ${Number(mainBalance) / 1e9} TON`);

        const topUp = toNano(FUND_TON) - balanceBefore;
        console.log(`topping up provider with ${Number(topUp) / 1e9} TON`);

        const seqno = await retry(() => w.getSeqno());
        await retry(() =>
            w.sendTransfer({
                seqno,
                secretKey: mainKp.secretKey,
                sendMode: SendMode.PAY_GAS_SEPARATELY,
                messages: [
                    internal({
                        to: providerWallet.address,
                        value: topUp,
                        bounce: false,
                    }),
                ],
            }),
        );

        // Wait for provider balance to reflect the top-up.
        for (let i = 0; i < 40; i++) {
            await sleep(3000);
            const bal = await retry(() => client.getBalance(providerWallet.address));
            if (bal > balanceBefore) {
                console.log(`provider balance after top-up: ${Number(bal) / 1e9} TON`);
                break;
            }
        }
    }

    // Write PROVIDER_MNEMONIC / PROVIDER_ADDRESS back into .env.local
    // if not already present. Do not rewrite the file fully — append.
    if (!existing) {
        const current = fs.readFileSync(ENV_PATH, 'utf-8');
        const append =
            `\n# Auto-generated by scripts/gen-provider-wallet.ts (${new Date().toISOString()})\n` +
            `PROVIDER_MNEMONIC="${providerWords.join(' ')}"\n` +
            `PROVIDER_ADDRESS=${providerAddr}\n`;
        fs.writeFileSync(ENV_PATH, current + append);
        console.log('wrote PROVIDER_MNEMONIC + PROVIDER_ADDRESS to .env.local');
    }

    console.log('\n===== PROVIDER READY =====');
    console.log(`address: ${providerAddr}`);
    console.log(`explorer: https://${TESTNET ? 'testnet.' : ''}tonviewer.com/${providerAddr}`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
